### ISSUE TITLE
如何关闭歌词翻译

### ISSUE THREAD

**Issue by hepingtao** [darknessomi/musicbox#271]
如何关闭歌词翻译，修改历史有写这个功能，但是快捷键列表里找不到

**Comment by Saddam0523** [comment]
在配置文件里面(~/.netease-musicbox/config.json)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: hepingtaoSent: 2016年3月22日星期二 14:54To: darknessomi/musicboxReply To: darknessomi/musicbox‎Subject: [musicbox] 如何关闭歌词翻译 (#271)如何关闭歌词翻译，修改历史有写这个功能，但是快捷键列表里找不到

—You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub
